demo/src/main/java/com/tlcsdm/demo/ControlsFXSample.java
demo/src/main/java/com/tlcsdm/demo/FXCenterPanelService.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
smc/src/main/java/module-info.java

Fixes # frame模块 Sample接口设计调整，将业务相关接口下放
1. Sample接口重构

feat: Sample 设计调整

---

pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/HelloActionGroup.java
smc/src/main/java/module-info.java

fix: 优化模块配置

---

smc/src/main/java/module-info.java

feat: 修改module.info文件

---

smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java

fix: 修复check error

---

smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java
smc/src/main/java/com/tlcsdm/smc/SmcSamplerProject.java

Fixes #smc centerPanel 设计优化
1. centerPanel 改为ScrolPanel
2. welcome 内容优化

feat: smc centerPanel 设计

---

demo/src/main/java/com/tlcsdm/demo/FXCenterPanelService.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloHyperlinkLabel.java
frame/src/main/java/com/tlcsdm/frame/CenterPanelService.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/model/EmptyCenterPanel.java
smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java
smc/src/main/java/com/tlcsdm/smc/SmcSamplerProject.java

Fixes #优化CenterPanelService 接口设计
1. CenterPanelService setCenterPanel -> getCenterPanel
2. smc welcome内容完善，新增超链接的使用示例

fix: 优化CenterPanelService 接口设计

---

smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java

Fixes #方法名称优化
1. buildSampleTabContent -> buildSmcContent

style: 方法名称优化

---

smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java

Feat # 新增 MaskerPane 遮盖层
1. ...
2. ...
3. ...

feat: 新增 MaskerPane 遮盖层

---

smc/src/main/java/com/tlcsdm/smc/SmcSampler.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloActionGroup.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloPrefixSelection.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties

Feat: #新增 prefixSelection 组件demo
1. 新增HelloPrefixSelection demo
2. 国际化使用

feat: 新增 prefixSelection 组件demo

---

demo/src/main/java/com/tlcsdm/demo/ControlsFXSample.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloActionGroup.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloPrefixSelection.java

Feat #菜单排序接口优化
1. Sample 新增 getOrderKey接口

feat: 菜单排序接口优化

---

smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java

style: 补充javadoc

---

smc/src/main/java/com/tlcsdm/smc/SmcConfiguration.java
smc/src/main/java/module-info.java
smc/src/main/resources/META-INF/services/com.tlcsdm.frame.FXSamplerConfiguration
smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

feat: configration接口实现

---

demo/src/main/java/com/tlcsdm/demo/FXMenubarConfigration.java
frame/src/main/java/com/tlcsdm/frame/MenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/module-info.java

Feat #about功能初始实现
1. setMenuBar 接口增强
2. about弹窗初实现

feat: about功能初始实现

---

smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

Fixes #修复css错误， 完善菜单栏国际化
1. smc 模块css修复
2. smc about 信息国际化完善

fix: 修复css错误， 完善菜单栏国际化

---

smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties

feat: 新增语言功能

---

.github/labeler.yml
.github/workflows/changelog.yml
.github/workflows/codacy-analysis.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/contributors.yml
.github/workflows/linter.yml
README.md

feat: 完善工作流

---

demo/src/main/java/com/tlcsdm/demo/samples/HelloGridView.java

fix: 修复路径错误

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/module-info.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java

feat: frame新增关闭和确认关闭功能

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/util/DiffHandleUtils.java
smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

feat: 文件比对初步实现

---

.github/labeler.yml
core/pom.xml
core/src/main/java/com/tlcsdm/core/javafx/FxApp.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/FxAlerts.java
core/src/main/java/com/tlcsdm/core/javafx/helper/LayoutHelper.java
core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/JavaFxSystemUtil.java
core/src/main/java/module-info.java
core/src/main/resources/logback.xml
demo/src/main/java/com/tlcsdm/demo/FXCenterPanelService.java
demo/src/main/java/com/tlcsdm/demo/FXMenubarConfigration.java
frame/pom.xml
frame/src/main/java/com/tlcsdm/frame/CenterPanelService.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/MenubarConfigration.java
frame/src/main/java/com/tlcsdm/frame/model/EmptyCenterPanel.java
pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/SmcCenterPanelService.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java

feat: 新增core模块

---

.github/workflows/changelog.yml

feat: 修改工作流组件

---

.mergify.yml

docs(workflow): Update .mergify.yml

---

.mergify.yml

docs: Update .mergify.yml

---

.mergify.yml

docs: update mergify.yml

---

.github/boring-cyborg.yml

docs: Update boring-cyborg.yml

---

.mergify.yml

docs: update workflow

---

.mergify.yml
pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/module-info.java

feat: code style组件完善

---

.mergify.yml

docs: 工作流完善

---

smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/module-info.java

feat: code style 组件完善

---

demo/src/main/java/com/tlcsdm/demo/ControlsFXSample.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloActionGroup.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloPrefixSelection.java
smc/src/main/java/com/tlcsdm/smc/tools/HelloSearchableComboBox.java

feat: 新增getSampleId接口

---

pom.xml
smc/pom.xml

新增hutool-dfa依赖
Fixes #
1. ...
2. ...
3. ...

build: 依赖完善

---

core/src/main/java/com/tlcsdm/core/javafx/dialog/ExceptionDialog.java
core/src/main/java/module-info.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretTest.java

fix: girret review bug修复

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/javafx/control/DoubleSpinner.java
core/src/main/java/com/tlcsdm/core/javafx/control/IntegerSpinner.java
core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
core/src/test/java/com/tlcsdm/core/util/FxXmlUtilTest.java
smc/src/main/java/com/tlcsdm/smc/tools/TestSpecGeneral.java

feat: XMLPropertiesConfiguration 测试以及配置

---

core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
core/src/main/java/module-info.java

feat: xml配置文件工具

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java

feat: FxXmlUtil工具类完善

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/SmcSample.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/tools/SpecGeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/MoneyToChineseTest.java

feat: 用户数据方案初步设计以及计划新增数字转换中文文字的功能

---

core/src/main/java/com/tlcsdm/core/util/MoneyToChineseUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/MoneyToChineseTest.java
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/SmcSample.java

完善smc initializeUserData方法
Fixes #
1. ...
2. ...
3. ...

feat: 新增money2ChineseUtil工具类

---

core/src/main/java/com/tlcsdm/core/exception/CoreException.java
core/src/main/java/com/tlcsdm/core/exception/ResourceNotFoundException.java
core/src/main/java/com/tlcsdm/core/exception/UnExpectedResultException.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/FxDialog.java
core/src/main/java/com/tlcsdm/core/javafx/helper/LayoutHelper.java
core/src/main/java/com/tlcsdm/core/javafx/util/FxmlUtil.java
core/src/main/java/module-info.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/tools/SpecGeneralTest.java

feat: core新增exception类

---

smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java

feat: smc fileDiff 集成 userData功能

---

smc/src/main/java/com/tlcsdm/smc/SmcSample.java

feat: 增强userData xml数据结构，新增保存顺序

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java

feat: codeStyle120 支持保留用户数据，后续需要调试

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java

fix: 解决configuration2 加载list数据toString的问题

---

core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/SmcSample.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties
smc/src/test/java/com/tlcsdm/smc/tool/APIHeaderCommentTest.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceXmlTest.java

feat: smc girretReview userData支持，新增查看用户数据菜单

---

demo/src/main/java/com/tlcsdm/demo/ControlsFXSample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
frame/src/main/java/module-info.java
smc/src/main/java/com/tlcsdm/smc/SmcSample.java

build: userData功能调整到frame模块

---

pom.xml

doc: update desc

---

smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java

feat: pin 内容处理

---

smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java

test: PinAssignment完善

---

smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java

feat: PinAssignment pin处理工具完成

---

core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java

feat: data文件中新增注释

---

core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java
smc/src/test/java/com/tlcsdm/smc/tool/HexText.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceDTSU2CXmlTest.java

test: 新增hex和DTS U2C 生成xml测试类

---

smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/tools/SpecGeneralTest.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties

feat: SpecGeneralTest初步实现以及filediff优化

---

core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java

feat: 新增CoreUtil

---

smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java

feat: 优化about action中图片获取方式

---

core/src/main/java/com/tlcsdm/core/javafx/helper/ImageHelper.java
core/src/main/java/com/tlcsdm/core/javafx/helper/LayoutHelper.java
core/src/main/java/com/tlcsdm/core/javafx/helper/MenuHelper.java

新增ImageHelper和MenuHelper
Fixes #
1. ...
2. ...
3. ...

feat: core helper包增强

---

smc/src/main/java/com/tlcsdm/smc/tools/SpecGeneralTest.java

feat: SpecGeneralTest功能实现完成

---

smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java
smc/src/main/java/module-info.java

feat: 修改smc下包名test -> unitTest

---

frame/src/main/java/com/tlcsdm/frame/model/Project.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DtsTriggerSourceXml.java
smc/src/main/java/module-info.java

feat: 新增DtsTriggerSourceXml组件

---

smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/module-info.java

feat: DtsTriggerSourceDoc组件初始化

---

smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java

test: 新增Dma triggersource code测试类

---

smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java

test: DMATriggerSourceCode 测试类完成

---

core/src/main/java/com/tlcsdm/core/factory/InitializingFactory.java
core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java
core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/main/java/module-info.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

feat: 新增InitializingFactory初始化接口以及线程池初始化实现

---

core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
frame/src/main/java/com/tlcsdm/frame/util/SampleScanner.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java

feat: 线程池设置为懒汉单例

---

core/src/test/java/com/tlcsdm/core/util/CryptoTest.java
demo/src/main/java/com/tlcsdm/demo/ControlsFXSample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java

des -> aes
Fixes #
1. ...
2. ...
3. ...

feat: smc PasswordField 数据切换为aes加密

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/exception/CoreException.java
core/src/main/java/com/tlcsdm/core/exception/ResourceNotFoundException.java
core/src/main/java/com/tlcsdm/core/exception/UnsupportedFeatureException.java
core/src/main/java/com/tlcsdm/core/factory/config/TemplateLoaderScanner.java
core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java
core/src/main/java/com/tlcsdm/core/util/FreemarkerUtil.java
core/src/main/resources/com/tlcsdm/core/static/templates/copyright.ftl
core/src/main/resources/com/tlcsdm/core/static/templates/license.ftl
pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/resources/com/tlcsdm/smc/static/templates/license.ftl

feat: 完善Freemarker 设计，新增jaxen支持XPath

---

pom.xml

build: 新增cache依赖

---

core/pom.xml
core/src/test/java/com/tlcsdm/core/util/AviatorTest.java
pom.xml
smc/src/main/resources/logback.xml

feat: 新增规则引擎aviator以及logback配置去除configruation2启动异常日志

---

pom.xml

feat: 新增tlcsdm-asyncTool依赖

---

core/src/main/java/com/tlcsdm/core/freemarker/TemplateLoaderService.java
pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java

style: 修复格式错误

---

pom.xml

docs: 修改依赖注释

---

demo/src/main/java/com/tlcsdm/demo/ControlsFXSamplerProject.java
frame/src/main/java/com/tlcsdm/frame/FXSamplerConfiguration.java
frame/src/main/java/com/tlcsdm/frame/FXSamplerProject.java
smc/src/main/java/com/tlcsdm/smc/SmcSamplerProject.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties

feat: 优化getWelcomeBackgroundImagePane接口

---

core/src/main/java/com/tlcsdm/core/javafx/FxApp.java
core/src/main/java/com/tlcsdm/core/logging/logback/base.xml
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/FXSamplerConfiguration.java
smc/src/main/java/com/tlcsdm/smc/SmcConfiguration.java
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/skin/MistSilverSkin.java
smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_en.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_ja.properties
smc/src/main/resources/com/tlcsdm/smc/i18n/messages_zh.properties
smc/src/main/resources/logback.xml

feat: logo以及名称抽象化，smc新增测试组件

---

README.md
core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlUtil.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java
smc/src/main/java/module-info.java

feat: 新增bindUserData增强方法，smc girretReview优化token信息初始化

---

core/src/main/java/com/tlcsdm/core/javafx/util/Config.java

docs: 注释修改

---

.gitignore
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/resources/logback.xml

feat: 修复girret启动问题

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/factory/config/TemplateLoaderScanner.java
core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java
core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/main/java/module-info.java
core/src/main/resources/com/tlcsdm/core/static/templates/copyright.ftl
core/src/main/resources/com/tlcsdm/core/static/templates/license.ftl
demo/pom.xml
demo/src/main/java/com/tlcsdm/demo/samples/actions/HelloActionProxy.java
demo/src/main/java/module-info.java
frame/src/main/java/com/tlcsdm/frame/util/SampleScanner.java
pom.xml
smc/src/main/java/com/tlcsdm/smc/config/SmcTemplateLoaderProvider.java
smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF
smc/src/main/resources/com/tlcsdm/smc/static/templates/license.ftl
smc/src/main/resources/logback.xml

fix: 修复打包问题，以及打包后template加载器错误

---

.github/labeler.yml
docs/smc/run/README.md
docs/smc/run/smcTool.bat
docs/smc/run/smcTool.vbs

docs: 新增运行文档

---

core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java

feat: DtsTriggerSourceDoc 功能完善

---

core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DtsTriggerSourceXml.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/HconvertExcel.java
smc/src/test/java/com/tlcsdm/smc/tool/HconvertExcel.java

feat: HconvertExcel 测试类完成

---

smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java

test: 新增PropertySheet 测试

---

smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java

test: 组件测试

---

smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java

fix: 修复smc StdtriggerSourceDoc 生成错误

---

core/src/main/java/com/tlcsdm/core/javafx/control/ProgressStage.java
core/src/main/resources/com/tlcsdm/core/i18n/messages_en.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_ja.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_zh.properties
core/src/test/resources/freemarker/templates/test1.ftl
smc/src/main/java/com/tlcsdm/smc/tools/TestTool.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java

close #302
Fixes #
1. ...
2. ...
3. ...

feat: 新增ProgressStage 加载组件

---

.github/labeler.yml

build: 新增i18ns标签

---

smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

fix: 修复smc general #ifndef相关判断

---

core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/SmcMenubarConfigration.java
smc/src/main/java/com/tlcsdm/smc/SmcSample.java
smc/src/main/resources/META-INF/MANIFEST.MF

新增maven-jar-plugin插件
Fixes #
1. ...
2. ...
3. ...

build: 修改ManIFEST.MF信息，修改smc 的发布和版本获取方式

---

core/src/main/java/module-info.java
frame/src/main/java/module-info.java
pom.xml
smc/src/main/java/module-info.java

chore: hutool版本升级到5.8.15, moduleName修改

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java

feat: DmaTriggerSourceCode 组件新增

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java

feat: dmaTeiggerSourceCode UI完善

---

README.md

docs: readme.md の更新

---

smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/dmaTriggerSourceCode/setting.ftl

feat: DmaTriggerSourceCode 模板完善

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java

feat: DmaTriggerSourceCode setting完善

---

.gitattributes

feat: Add .gitattributes

---

.gitattributes

feat: update .gitattributes

---

.github/boring-cyborg.yml

chore: Update boring-cyborg.yml

---

.mergify.yml

docs: update mergify

---

.github/workflows/changelog.yml

chore: workflow changelog update

---

pom.xml

chore: Update javafx to 17.0.2

---

smc/src/test/java/com/tlcsdm/smc/tool/tool/GithubApiTest.java

test: 新增github api测试

---

smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/dmaTriggerSourceCode/binding_selRegNum.ftl

fix: dmaTriggerSourceCode模板完善

---

smc/src/test/java/com/tlcsdm/smc/tool/ecm/C1MEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/resources/templates/ecm/c1m.ftl

test: ecm测试类修改

---

core/src/main/java/com/tlcsdm/core/javafx/dialog/LogConsoleDialog.java
smc/src/test/java/com/tlcsdm/smc/tool/tool/GithubApiTest.java

style: 代码格式优化

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java

style: 窗口大小调整

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/dmaTriggerSourceCode/cgdma.ftl

fix: DmaTriggerSourceCode 头文件模板新增注释

---

smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

在选中只生成文件时，打开输出位置到files文件夹
Fixes #401
1. ...
2. ...
3. ...

feat: specGeneral 打开输出位置功能增强

---

.github/workflows/maven.yml

chore: Update workflow

---

smc/src/main/java/com/tlcsdm/smc/SmcSample.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java

fix: 解决打包为执行文件后项目配置获取不到的问题

---

smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java

fix: 修复DtsTriggerSourceDoc 初始值设定的判断问题

---

smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/resources/templates/ecm/c1m.ftl
smc/src/test/resources/templates/ecm/u2a.ftl

test: 完善ecm脚本测试

---

smc/src/main/java/module-info.java

style: 代码格式化

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/JacksonTest.java
core/src/test/java/com/tlcsdm/core/util/UserInfo.java
pom.xml

feat: 新增jackson依赖以及工具类

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DtsTriggerSourceXml.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2AEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java
smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/ecm/c1m.ftl
smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/ecm/u2a.ftl

Fixes #370
1. ...
2. ...
3. ...

feat: Ecm功能实现

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java

fix: 修复ecm模板下载失败问题

---

pom.xml
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java

feat: 修改ecm脚本

---

README.md

docs: 完善README.md

---

README.md
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/model/SampleTreeViewModel.java
frame/src/main/java/com/tlcsdm/frame/service/SamplesTreeViewConfiguration.java
frame/src/main/java/module-info.java
pom.xml
smc/src/main/java/com/tlcsdm/smc/provider/SmcSampleTreeViewConfiguration.java
smc/src/main/java/module-info.java
smc/src/main/resources/META-INF/services/com.tlcsdm.frame.service.SamplesTreeViewConfiguration

feat: 新增SamplesTreeViewConfiguration接口

---

core/pom.xml
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2AEcmScript.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/C1MEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java

feat: ecm脚本修改

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2AEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/MoneyToChinese.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

feat: 隐藏moneyToChinese组件

---

.github/workflows/codeql-analysis.yml

chore: update codeql-analysis.yml

---

frame/src/main/resources/com/tlcsdm/frame/static/bootstrap2.css
frame/src/main/resources/com/tlcsdm/frame/static/nord-dark.css
frame/src/main/resources/com/tlcsdm/frame/static/nord-light.css
frame/src/main/resources/com/tlcsdm/frame/static/primer-dark.css
frame/src/main/resources/com/tlcsdm/frame/static/primer-light.css
smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

style: 样式调整

---

smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

style: 修改control-textarea样式

---

core/src/main/java/com/tlcsdm/core/javafx/bind/CheckBoxSelectedBinding.java
core/src/main/java/com/tlcsdm/core/javafx/bind/ComboBoxBaseEmptyBinding.java
core/src/main/java/com/tlcsdm/core/javafx/bind/FxBindingBuilder.java
core/src/main/java/com/tlcsdm/core/javafx/bind/FxBooleanBindingBuilder.java
core/src/main/java/com/tlcsdm/core/javafx/bind/MultiTextInputControlEmptyBinding.java
core/src/main/java/com/tlcsdm/core/javafx/bind/TextInputControlEmptyBinding.java
core/src/main/java/module-info.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DtsTriggerSourceXml.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/ExcelColNameCalculator.java
smc/src/main/java/com/tlcsdm/smc/tools/FileDiff.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/tools/MoneyToChinese.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/HconvertExcel.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

Fixes #458
1. ...
2. ...
3. ...

feat: 完善DMATriggerSourceCode 的bind

---

pom.xml

chore: javafx 17.0.2 -> 17.0.6

---

pom.xml

chore: 新增RichTextfx

---

qe/src/main/resources/com/tlcsdm/qe/i18n/messages_en.properties
qe/src/main/resources/com/tlcsdm/qe/i18n/messages_ja.properties
qe/src/main/resources/com/tlcsdm/qe/i18n/messages_zh.properties

style: 样式修改

---

.github/workflows/codeql.yml

chore: Create .github/workflows/codeql.yml

---

.github/workflows/codeql.yml

chore: Update codeql.yml

---

qe/src/main/java/com/tlcsdm/qe/tools/HtmlEscape.java

style: Update HtmlEscape.java

---

pom.xml

chore: Update pom.xml

---

common/src/main/java/com/tlcsdm/jfxcommon/provider/CommonSamplerProjectProvider.java
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_en.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_ja.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_zh.properties

feat: 完善common模块

---

smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java
smc/src/test/resources/templates/ecm/u2c.ftl

feat: 完善ecm u2c

---

core/src/main/java/com/tlcsdm/core/util/Dom4jUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/Dom4jTest.java
core/src/test/resources/util/dom4j/students.xml
core/src/test/resources/util/dom4j/students_copy.xml

test: dom4j测试工具

---

core/pom.xml
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/jexl/ArrayTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlDemo.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/MethodPropertyTest.java
pom.xml

Fixes #501
1. ...
2. ...
3. ...

test: jexl测试工具

---

.gitattributes

docs: Update .gitattributes

---

core/src/main/java/module-info.java
core/src/main/resources/com/tlcsdm/core/groovy/SimpleHttpServer.groovy

feat(core): 新增SimpleHttpServer脚本

---

.editorconfig

chore: Create .editorconfig

---

.editorconfig

chore: Update .editorconfig

---

core/pom.xml
core/src/test/resources/groovy/DateDemo.groovy
pom.xml

chore: 补充groovy依赖

---

core/src/test/resources/groovy/ArrayDemo.groovy
core/src/test/resources/groovy/MapDemo.groovy

test: 新增groovy示例

---

smc/src/main/resources/com/tlcsdm/smc/static/templates/smc/ecm/c1m.ftl
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java
smc/src/test/resources/templates/ecm/c1m.ftl
smc/src/test/resources/templates/ecm/u2c.ftl

test: ecm u2c测试类

---

demo/src/main/java/com/tlcsdm/demo/samples/spreadsheet/HelloSpreadsheetView2.java
demo/src/main/java/com/tlcsdm/demo/samples/tableview2/HelloFilteredTableView.java
demo/src/main/java/com/tlcsdm/demo/samples/tableview2/HelloTableView2.java

style: 代码样式修改

---

core/src/test/java/com/tlcsdm/core/util/MyTest.groovy

test: 修改测试脚本

---

core/src/test/java/com/tlcsdm/core/util/FxXmlUtilTest.java
smc/src/test/java/com/tlcsdm/smc/tool/CodeStyleLength120Test.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATemplateTriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSU2CTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretTest.java
smc/src/test/java/com/tlcsdm/smc/tool/HconvertExcel.java
smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceDTSU2CXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/C1MEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java

test: 测试使能调整

---

.github/workflows/maven.yml
core/src/test/java/com/tlcsdm/core/util/MyTest.groovy
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyClassLoaderTest.java
smc/src/test/java/com/tlcsdm/smc/tool/CodeStyleLength120Test.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATemplateTriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSU2CTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretTest.java
smc/src/test/java/com/tlcsdm/smc/tool/HconvertExcel.java
smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceDTSU2CXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/C1MEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java

test: 修改测试工作流

---

.github/workflows/maven.yml
core/src/test/java/com/tlcsdm/core/util/FreemarkerTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyClassLoaderTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyScriptEngineTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyShellTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyUtilTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/JSR223Test.java
core/src/test/java/com/tlcsdm/core/util/jexl/ArrayTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlDemo.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/MethodPropertyTest.java

test: 测试工作流调整

---

.github/workflows/maven.yml
core/src/test/java/com/tlcsdm/core/util/AviatorTest.java
core/src/test/java/com/tlcsdm/core/util/Dom4jTest.java
core/src/test/java/com/tlcsdm/core/util/FreemarkerTest.java
core/src/test/java/com/tlcsdm/core/util/MoneyToChineseTest.java
core/src/test/java/com/tlcsdm/core/util/MyTest.groovy
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyClassLoaderTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyScriptEngineTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyShellTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyUtilTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/JSR223Test.java
core/src/test/java/com/tlcsdm/core/util/jexl/ArrayTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlDemo.java
core/src/test/java/com/tlcsdm/core/util/jexl/JexlTest.java
core/src/test/java/com/tlcsdm/core/util/jexl/MethodPropertyTest.java
pom.xml
smc/src/test/java/com/tlcsdm/smc/tool/CodeStyleLength120Test.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATemplateTriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DMATriggerSourceCode.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSU2CTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretTest.java
smc/src/test/java/com/tlcsdm/smc/tool/HconvertExcel.java
smc/src/test/java/com/tlcsdm/smc/tool/PinAssignment.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceDTSU2CXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/TriggerSourceXmlTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/C1MEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java

chore: 修改工作流

---

qe/src/main/java/com/tlcsdm/qe/config/QeTreeViewCellFactory.java
smc/src/test/java/com/tlcsdm/smc/tool/tool/GithubApiTest.java

feat: qe新增右键菜单

---

pom.xml

chore: maven版本管理修改

---

qe/src/main/resources/com/tlcsdm/qe/fxsampler/fxsampler.css

style(qe): 修改样式

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractU2XFamilyScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2CEcmScript.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2AEcmTest.java
smc/src/test/java/com/tlcsdm/smc/tool/ecm/U2CEcmTest.java

feat(smc): ecm脚本修改

---

pom.xml
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java

还有值去空串以及多余的double提示去除
Fixes #
1. ...
2. ...
3. ...

feat(smc): girret增强

---

smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java

修复变量初始化时机
Fixes #
1. ...
2. ...
3. ...

feat(smc): girret repo条件增强

---

core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java

feat: 线程池uncaughtExceptionHandler属性配置

---

core/src/main/resources/com/tlcsdm/core/groovy/SimpleHttpServer.groovy
core/src/test/java/com/tlcsdm/core/util/groovy/GroovyClassLoaderTest.java
core/src/test/java/com/tlcsdm/core/util/groovy/JSR223Test.java
core/src/test/resources/groovy/hello2.groovy
demo/src/main/java/com/tlcsdm/demo/samples/HelloGlyphFont.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloGridView.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloInfoOverlay.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloMaskerPane.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloNotifications.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloPlusMinusSlider.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloPrefixSelection.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloPropertySheet.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloSegmentedBar.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloTaskProgressView.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloValidation.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloWorldMapView.java
demo/src/main/java/com/tlcsdm/demo/samples/actions/HelloActionGroup.java
demo/src/main/java/com/tlcsdm/demo/samples/actions/HelloActionProxy.java
demo/src/main/java/com/tlcsdm/demo/samples/checked/HelloCheckComboBox.java
demo/src/main/java/com/tlcsdm/demo/samples/checked/HelloCheckTreeView.java
demo/src/main/java/com/tlcsdm/demo/samples/dialogs/HelloDialogs.java
demo/src/main/java/com/tlcsdm/demo/samples/spreadsheet/HelloSpreadsheetView.java
demo/src/main/java/com/tlcsdm/demo/samples/tableview2/HelloFilteredTableView.java
demo/src/main/java/com/tlcsdm/demo/samples/tableview2/HelloTableView2.java
docs/lib/docsify-pdf-embed.js
smc/src/test/java/com/tlcsdm/smc/tool/CodeStyleLength120Test.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/DTSU2CTriggerSourceDocument.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretTest.java

style: 静默代码清理

---

pom.xml

chore: 修改ikonli依赖

---

core/src/main/java/com/tlcsdm/core/util/DiffHandleUtils.java

feat(core): DiffHandleUtils优化

---

core/src/main/java/com/tlcsdm/core/util/Dom4jUtil.java

Fixes #571
1. ...
2. ...
3. ...

fix(core): 修复Dom4jUtil的漏洞

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiff.java
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/com/tlcsdm/core/util/DiffHandleUtil.java
core/src/main/java/com/tlcsdm/core/util/Dom4jUtil.java
core/src/main/java/com/tlcsdm/core/util/FreemarkerUtil.java
core/src/main/java/com/tlcsdm/core/util/GroovyUtil.java
core/src/main/java/com/tlcsdm/core/util/HtmlUtil.java
core/src/main/java/com/tlcsdm/core/util/I18nUtils.java
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/com/tlcsdm/core/util/MoneyToChineseUtil.java
core/src/main/java/com/tlcsdm/core/util/MultiMap.java
pom.xml
smc/src/main/java/com/tlcsdm/smc/provider/SmcSamplePostProcessorProvider.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/APIHeaderCommentTest.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java

feat: 导入优化

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlHelper.java
core/src/main/java/com/tlcsdm/core/util/DiffHandleUtil.java
core/src/main/java/com/tlcsdm/core/util/Dom4jUtil.java

fix: 修复dom4j工具漏洞

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiff.java
core/pom.xml
core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlHelper.java
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/com/tlcsdm/core/util/DiffHandleUtil.java
core/src/main/java/com/tlcsdm/core/util/Dom4jUtil.java
core/src/main/java/com/tlcsdm/core/util/FreemarkerUtil.java
core/src/main/java/com/tlcsdm/core/util/GroovyUtil.java
core/src/main/java/com/tlcsdm/core/util/HtmlUtil.java
core/src/main/java/com/tlcsdm/core/util/I18nUtils.java
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/com/tlcsdm/core/util/MoneyToChineseUtil.java
core/src/main/java/com/tlcsdm/core/util/MultiMap.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/PdfboxTest.java
pom.xml
qe/pom.xml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/provider/SmcSamplePostProcessorProvider.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java
smc/src/test/java/com/tlcsdm/smc/tool/APIHeaderCommentTest.java
smc/src/test/java/com/tlcsdm/smc/tool/GeneralTest.java

Fixes #384
1. ...
2. ...
3. ...

feat(core): PDFBox支持

---

common/src/test/java/com/tlcsdm/jfxcommon/DemoTest.java
common/src/test/resources/File.groovy

test: 新增common测试包

---

core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/FxDialog.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/PathWatchToolDialog.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java

feat: PathWatchTool完善

---

common/pom.xml
core/src/main/java/com/tlcsdm/core/util/DiffHandleUtil.java
qe/src/main/resources/logback.xml
smc/pom.xml
smc/src/main/resources/logback.xml

feat: 彩色日志

---

.editorconfig

build: Update .editorconfig

---

core/src/main/java/com/tlcsdm/core/javafx/controller/PathWatchToolController.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/ExceptionDialog.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/FxAlerts.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/PathWatchToolDialog.java
core/src/main/java/com/tlcsdm/core/javafx/service/PathWatchListener.java
core/src/main/java/com/tlcsdm/core/javafx/service/PathWatchToolService.java
core/src/main/java/module-info.java
core/src/main/resources/com/tlcsdm/core/fxml/PathWatchTool.fxml
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
pom.xml
qe/src/main/java/com/tlcsdm/qe/provider/QeVersionCheckerProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcVersionCheckerProvider.java

feat: 新增中断异常处理

---

.github/boring-cyborg.yml
.github/labeler.yml
README.md
README_zh.md
core/src/main/java/com/tlcsdm/core/javafx/controller/PathWatchToolController.java
core/src/main/java/com/tlcsdm/core/javafx/service/PathWatchToolService.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

docs: readme更新

---

README.md
README_zh.md

docs: 修改README

---

smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

build: smc-1.0.3 release

---

pom.xml

docs: Update pom.xml

---

smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

build: Upgrade Specgeneral

---

core/src/main/java/module-info.java
docs/README.md

docs: Documentation promotion

---

core/pom.xml
pom.xml

chore: richtextfx依赖支持

---

core/pom.xml
core/src/main/java/module-info.java
pom.xml

feat(core): richtextfx支持

---

core/pom.xml
pom.xml

Fixes #587 
1. ...
2. ...
3. ...

chore: caffeine依赖支持

---

.github/workflows/stale.yml

build: Update stale.yml

---

docs/README.md

docs: 更新文档

---

core/src/main/java/com/tlcsdm/core/javafx/control/LineChartWithMarkers.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java
qe/src/main/java/module-info.java
qe/src/main/resources/com/tlcsdm/qe/fxml/light.css
qe/src/main/resources/com/tlcsdm/qe/fxml/light.fxml
qe/src/main/resources/com/tlcsdm/qe/static/icon/lighting.svg

feat(frame): Add rightPane control interface

---

core/src/main/java/com/tlcsdm/core/javafx/control/HyperlinkTableCell.java
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java

feat(smc): 关于界面增加开源项目依赖视图

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2CEcmScript.java

fix(smc): U2C数据特殊处理

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2CEcmScript.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

style: code format

---

core/src/main/java/com/tlcsdm/core/javafx/control/DependencyTableView.java
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
qe/pom.xml
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
qe/src/main/java/com/tlcsdm/qe/provider/QeVersionCheckerProvider.java
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcVersionCheckerProvider.java
smc/src/main/java/module-info.java

feat: Add Dependency tableView modal

---

core/src/main/java/com/tlcsdm/core/javafx/control/HyperlinkTableCell.java

feat: Improve HyperlinkTableCell

---

core/pom.xml
pom.xml

chore: 依赖冲突解决

---

qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java
qe/src/main/resources/com/tlcsdm/qe/fxml/light.css
qe/src/main/resources/com/tlcsdm/qe/fxml/light.fxml

test: modify demo for fxml

---

core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/CaffeineTest.java

feat: 新增Order注解

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java

docs: Update DependencyInfo.java

---

core/src/main/java/com/tlcsdm/core/event/ApplicationEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationFailedEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationPreparedEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationReadyEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationStartingEvent.java
core/src/main/java/com/tlcsdm/core/eventbus/AsyncEventBus.java
core/src/main/java/com/tlcsdm/core/eventbus/EventBus.java
core/src/main/java/com/tlcsdm/core/eventbus/ObserverAction.java
core/src/main/java/com/tlcsdm/core/eventbus/ObserverRegister.java
core/src/main/java/com/tlcsdm/core/eventbus/Subscribe.java
core/src/main/java/com/tlcsdm/core/javafx/service/PathWatchToolService.java
core/src/main/java/module-info.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

feat(core): Add EventBus

---

core/src/main/java/com/tlcsdm/core/event/ApplicationEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationFailedEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationPreparedEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationReadyEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationStartingEvent.java
core/src/main/java/com/tlcsdm/core/eventbus/AsyncEventBus.java
core/src/main/java/com/tlcsdm/core/eventbus/EventBus.java
core/src/main/java/com/tlcsdm/core/eventbus/ObserverAction.java
core/src/main/java/com/tlcsdm/core/eventbus/ObserverRegister.java
core/src/main/java/com/tlcsdm/core/eventbus/Subscribe.java

docs: Add docs

---

core/src/main/java/com/tlcsdm/core/javafx/dialog/LicenseDialog.java
core/src/main/java/com/tlcsdm/core/util/CoreConstant.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

feat(core): Add LicenseDialog

---

core/src/main/java/com/tlcsdm/core/factory/config/GroovyLoaderScanner.java
core/src/main/java/com/tlcsdm/core/factory/config/TemplateLoaderScanner.java
core/src/main/java/com/tlcsdm/core/util/GroovyUtil.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

feat: 优化加载类

---

core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/resources/com/tlcsdm/core/i18n/messages_en.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_ja.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_zh.properties
docs/README.md
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java
smc/src/main/java/module-info.java

feat(smc): 新增帮助文档

---

smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

build(smc): prepare for 1.0.6

---

core/src/main/java/com/tlcsdm/core/util/GroovyUtil.java

test(core): 修改simpleHttpServer

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md
pom.xml

feat: Upgrade pdfbox

---

core/src/main/java/com/tlcsdm/core/util/CoreUtil.java

在jar运行环境下，根路径获取错误
Fixes #682 
1. ...
2. ...
3. ...

fix(core): 修复CoreUtil.getRootPath()问题

---

frame/pom.xml
pom.xml

chore: modify preferencesfx

---

core/src/main/java/com/tlcsdm/core/factory/config/GroovyLoaderScanner.java
core/src/main/java/com/tlcsdm/core/groovy/GroovyLoaderService.java
core/src/main/java/com/tlcsdm/core/util/GroovyUtil.java
qe/src/main/java/com/tlcsdm/qe/config/QeGroovyLoaderProvider.java
smc/src/main/java/com/tlcsdm/smc/config/SmcGroovyLoaderProvider.java

String[]的有参构造中createRoot对jar下的URL解析有问题
Fixes #677 
1. ...
2. ...
3. ...

fix(core): 修复groovy路径扫描错误的问题

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java

feat(smc): ecm 优化

---

README.md
README_jp.md
README_zh.md

docs: 更新README

---

core/src/main/java/com/tlcsdm/core/javafx/controller/CoreStorageHandler.java
core/src/main/java/com/tlcsdm/core/javafx/controller/PreferencesView.java
core/src/main/java/com/tlcsdm/core/javafx/stage/ScreenshotStage.java
core/src/main/java/com/tlcsdm/core/javafx/util/Config.java
core/src/main/java/com/tlcsdm/core/javafx/util/JavaFxSystemUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/Keys.java
core/src/main/java/com/tlcsdm/core/javafx/util/StageUtil.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

style: Config代码结构优化

---

smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

build(smc): Prepare for 1.0.7

---

core/src/main/java/com/tlcsdm/core/javafx/richtext/GroovyCodeArea.java
core/src/main/resources/com/tlcsdm/core/static/javafx/richtext/java-keywords.css

fix(core): 修复groovyCodeArea处理开头版权信息时堆栈溢出问题

---

.github/workflows/changelog.yml

build: 修改changelog工作流

---

CHANGELOG.md

docs(changelog): Update release notes

docs(changelog): Update release notes

---

.github/workflows/automerge.yml
.github/workflows/contributors.yml
.github/workflows/issue-labeled.yml
.github/workflows/label.yml
.github/workflows/linter.yml
.github/workflows/stale.yml

build: 修改工作流令牌

---

core/src/main/java/com/tlcsdm/core/javafx/dialog/LicenseDialog.java

fix(core): 修复LicenseDialog样式问题

---

core/src/main/java/com/tlcsdm/core/javafx/richtext/GroovyCodeArea.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #707
1. ...
2. ...
3. ...

feat(core): groovyCodeArea 注释收缩样式

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
qe/src/main/java/com/tlcsdm/qe/provider/QeSplashProvider.java

feat(frame): 启动动画支持

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
pom.xml

Fixes #578
1. ...
2. ...
3. ...

fix(frame): 修复启动图片关闭失败的问题

---

smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

build(smc): Prepare for 1.0.8

---

core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/FxButtonType.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/LicenseDialog.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/PathWatchToolDialog.java
core/src/main/resources/com/tlcsdm/core/i18n/messages_en.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_ja.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_zh.properties
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

ButtonType的国际化跟系统语言一致而不是软件所选语言
Fixes #
1. ...
2. ...
3. ...

feat(smc): 修复按钮的国际化问题

---

.mergify.yml

build: Update .mergify.yml

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md

feat: 文档修改

---

.github/workflows/linter.yml

build: lint工作流修改

---

.github/linters/.markdown-lint.yml
.github/linters/sun_checks.xml
.github/workflows/linter.yml

build: linter工作流优化

---

.github/.mergify.yml
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/linter.yml

build: mergify工作流更新

---

.github/linters/sun_checks.xml
.github/workflows/linter.yml

build: suncheck工作流更新

---

.github/linters/sun_checks.xml
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
qe/src/main/java/com/tlcsdm/qe/tools/DaliDemo.java
qe/src/main/resources/com/tlcsdm/qe/fxml/daliConfig.fxml
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java

feat(qe): dali config添加

---

core/src/main/java/com/tlcsdm/core/javafx/bind/FxBindingBuilder.java
core/src/main/java/com/tlcsdm/core/javafx/bind/FxBooleanBindingBuilder.java
core/src/main/java/com/tlcsdm/core/javafx/control/ShadowScrollPane.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractU2XFamilyScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2AEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2CEcmScript.java

feat(frame): 接口权限控制

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/test/java/com/tlcsdm/core/util/CsvTest.java
docs/README.md
pom.xml

chore: Add commons-csv

---

.github/linters/sun_checks.xml
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

feat(smc): SpecGeneralTest UI使能条件优化

---

smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

feat(smc): specGeneral使能条件优化，功能优化

---

common/src/main/java/module-info.java
core/pom.xml
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/tool/GithubApiTest.java
core/src/test/java/com/tlcsdm/core/util/GithubApiTest.java
qe/pom.xml
qe/src/main/java/com/tlcsdm/qe/provider/QeVersionCheckerProvider.java
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
qe/src/main/java/module-info.java
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/provider/SmcVersionCheckerProvider.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/java/module-info.java

feat: jackson替换hutool-json

---

core/pom.xml
docs/README.md
pom.xml

chore: 依赖更新

---

.github/linters/sun_checks.xml
common/src/main/java/module-info.java
frame/pom.xml
frame/src/main/java/com/tlcsdm/frame/cache/SampleCache.java
frame/src/main/java/com/tlcsdm/frame/cache/SampleCacheFactory.java
frame/src/main/java/com/tlcsdm/frame/cache/impl/CaffeineSimpleCache.java
frame/src/main/java/com/tlcsdm/frame/cache/impl/SimpleSampleCache.java
frame/src/main/java/com/tlcsdm/frame/config/SampleTreeCache.java
frame/src/main/java/module-info.java
qe/src/main/java/com/tlcsdm/qe/provider/QeCenterPanelProvider.java
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/provider/SmcCenterPanelProvider.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/java/module-info.java

Fixes #746
1. ...
2. ...
3. ...

feat(frame): 新增菜单缓存

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/JacksonTest.java
core/src/test/java/com/tlcsdm/core/util/User.java
pom.xml

feat(core): Jackson配置优化

---

.github/workflows/maven.yml
core/src/main/java/com/tlcsdm/core/javafx/control/ProgressStage.java
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/test/java/com/tlcsdm/core/util/StringTokenizerTest.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/tools/girret/Change.java
smc/src/main/java/com/tlcsdm/smc/tools/girret/Comment.java
smc/src/main/java/com/tlcsdm/smc/tools/girret/CommentRange.java
smc/src/main/java/com/tlcsdm/smc/tools/girret/Owner.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/HconvertExcel.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java
smc/src/main/java/module-info.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretParserTest.java
smc/src/test/resources/girret/changes.json
smc/src/test/resources/girret/comments.json

Fixes #766, fixes #764
1. ...
2. ...
3. ...

feat(smc): girret工具bug修复

---

core/src/main/java/com/tlcsdm/core/javafx/control/ProgressStage.java

Fixes #768
1. ...
2. ...
3. ...

feat(core): ProgressStage增加高斯模糊效果

---

core/src/main/java/com/tlcsdm/core/javafx/FxApp.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #771
1. ...
2. ...
3. ...

feat(frame): 优化启动动画时的托盘图标

---

core/src/main/java/com/tlcsdm/core/javafx/util/FxXmlHelper.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
qe/src/main/java/com/tlcsdm/qe/tools/Compress.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

Fixes #776
1. ...
2. ...
3. ...

fix(core): 修复导入设置取消时的异常重启

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #775
1. ...
2. ...
3. ...

feat(frame): 隐藏闪屏的托盘图标

---

frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
frame/src/main/java/com/tlcsdm/frame/model/EmptySample.java
qe/src/main/java/com/tlcsdm/qe/tools/DaliDemo.java
qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java

feat(frame): 接口重命名

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #782 
1. ...
2. ...
3. ...

fix(frame): 修复mac arm环境下隐藏失败的问题

---

qe/src/main/java/com/tlcsdm/qe/provider/QeSplashProvider.java

feat(qe): 调整动画UI

---

common/pom.xml
common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiff.java
qe/pom.xml
smc/pom.xml

Fixes #786
1. ...
2. ...
3. ...

feat(common): common模块设计修改

---

.github/dependabot.yml
.github/workflows/maven.yml

build: 工作流修改

---

.github/dependabot.yml
.github/workflows/stale.yml

build: 修改工作流

---

qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
qe/src/main/resources/META-INF/MANIFEST.MF
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

build: prepare for release

---

core/src/main/java/com/tlcsdm/core/javafx/dialog/FxAlerts.java
pom.xml
qe/src/main/java/com/tlcsdm/qe/tools/DaliDemo.java
qe/src/main/java/com/tlcsdm/qe/tools/dali/AbstractDaliConfigurationController.java
qe/src/main/java/com/tlcsdm/qe/tools/dali/MemoryBankController.java
qe/src/main/java/com/tlcsdm/qe/tools/dali/VariableController.java
qe/src/main/resources/com/tlcsdm/qe/fxml/dali/memoryBank.fxml
qe/src/main/resources/com/tlcsdm/qe/fxml/dali/variable.fxml
qe/src/main/resources/com/tlcsdm/qe/fxml/daliConfig.css
qe/src/main/resources/com/tlcsdm/qe/fxml/daliConfig.fxml

feat(qe): DALI UI调整

---

.github/labeler.yml

build: Update workflow

---

pom.xml

build: Add swt

---

pom.xml
smc/pom.xml
smc/src/main/resources/META-INF/MANIFEST.MF

build: Modify build info

---

.github/linters/sun_checks.xml
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/Sample.java
frame/src/main/java/com/tlcsdm/frame/SampleBase.java
qe/src/main/java/com/tlcsdm/qe/tools/DaliDemo.java

Fixes #815
1. ...
2. ...
3. ...

test: Sample测试

---

pom.xml

chore: Add javafx-swt

---

pom.xml

build: 构建配置修改

---

core/src/main/java/module-info.java

build: 修改构建信息

---

cg/pom.xml
cg/src/main/resources/META-INF/MANIFEST.MF
common/pom.xml
core/pom.xml
demo/pom.xml
frame/pom.xml
login/pom.xml
pom.xml
qe/pom.xml
qe/src/main/resources/META-INF/MANIFEST.MF
smc/pom.xml
smc/src/main/resources/META-INF/MANIFEST.MF

Fixes #849
1. ...
2. ...
3. ...

build: 修改构建

---

.github/workflows/automerge.yml

build: Update automerge.yml

---

cg/pom.xml
pom.xml
qe/pom.xml
smc/pom.xml

Fixes #857
1. ...
2. ...
3. ...

build: 构建信息修改

---

core/src/test/java/com/tlcsdm/core/util/GitlabApiTest.java

test: fix code

---

cg/src/main/java/com/tlcsdm/cg/util/CgConstant.java
docs/index.html
pom.xml
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java

Fixes #870
1. ...
2. ...
3. ...

docs: 文档修改

---

SECURITY.md
cg/src/main/java/com/tlcsdm/cg/provider/CgMenubarConfigrationProvider.java
cg/src/main/java/com/tlcsdm/cg/util/CgConstant.java
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/ConfigLanguageAction.java
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxLanguageActionGroup.java
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/LanguageType.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java

Fixes #874
1. ...
2. ...
3. ...

feat: 语言切换功能集成

---

docs/README.md

Fixes #879
1. ...
2. ...
3. ...

docs: Update docs

---

CONTRIBUTORS.md

bot: Update Contributors File

---

.github/linters/.groovylintrc.json

build: Add groovy check

---

cg/pom.xml
cg/src/main/java/com/tlcsdm/cg/provider/CgMenubarConfigrationProvider.java
cg/src/main/java/com/tlcsdm/cg/util/CgConstant.java
core/src/main/java/com/tlcsdm/core/javafx/controller/PreferencesView.java
core/src/main/java/com/tlcsdm/core/javafx/controller/SystemSettingController.java
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/java/com/tlcsdm/core/javafx/dialog/SystemSettingDialog.java
core/src/main/java/com/tlcsdm/core/javafx/view/AbstractSystemSettingView.java
core/src/main/java/com/tlcsdm/core/javafx/view/SystemSettingView.java
core/src/main/resources/com/tlcsdm/core/fxml/SystemSetting.fxml

Fixes #826
1. ...
2. ...
3. ...

feat: Improve SystemSetting

---

cg/src/main/resources/com/tlcsdm/cg/fxsampler/fxsampler.css
core/src/main/java/com/tlcsdm/core/javafx/controller/SystemSettingController.java
core/src/main/java/com/tlcsdm/core/javafx/util/Keys.java
core/src/main/resources/com/tlcsdm/core/fxml/SystemSetting.fxml
core/src/main/resources/com/tlcsdm/core/i18n/messages_en.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_ja.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_zh.properties
core/src/main/resources/com/tlcsdm/core/static/javafx/richtext/properties.css
frame/src/main/java/com/tlcsdm/frame/model/FXSamplerTheme.java
frame/src/main/resources/com/tlcsdm/frame/static/css/bootstrap2.css
frame/src/main/resources/com/tlcsdm/frame/static/css/bootstrap3.css
frame/src/main/resources/com/tlcsdm/frame/static/css/cupertino-dark.css
frame/src/main/resources/com/tlcsdm/frame/static/css/cupertino-light.css
frame/src/main/resources/com/tlcsdm/frame/static/css/dracula.css
frame/src/main/resources/com/tlcsdm/frame/static/css/nord-dark.css
frame/src/main/resources/com/tlcsdm/frame/static/css/nord-light.css
frame/src/main/resources/com/tlcsdm/frame/static/css/primer-dark.css
frame/src/main/resources/com/tlcsdm/frame/static/css/primer-light.css
qe/src/main/resources/com/tlcsdm/qe/fxsampler/fxsampler.css
smc/src/main/java/com/tlcsdm/smc/provider/SmcConfigurationProvider.java
smc/src/main/resources/com/tlcsdm/smc/fxsampler/fxsampler.css

Fixes #843
1. ...
2. ...
3. ...

feat: Improve theme

---

.github/boring-cyborg.yml
smc/pom.xml
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java
smc/src/main/resources/META-INF/MANIFEST.MF

release: Smc 1.0.10

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java

docs: 文档更正

---

.github/labeler.yml
docs/README.md
docs/overview/Changelog.md

docs: 文档更新

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/com/tlcsdm/core/util/JaxbUtils.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/Book.java
core/src/test/java/com/tlcsdm/core/util/DateAdapter.java
core/src/test/java/com/tlcsdm/core/util/JaxbTest.java
docs/README.md
pom.xml

Fixes #890
1. ...
2. ...
3. ...

test: Add JAXB

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md

feat: Add docs

---

cg/src/main/java/com/tlcsdm/cg/provider/CgVersionCheckerProvider.java
frame/src/main/java/com/tlcsdm/frame/service/VersionCheckerService.java
pom.xml
qe/src/main/java/com/tlcsdm/qe/provider/QeVersionCheckerProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcVersionCheckerProvider.java

build: 修复eclipse 依赖检查错误

---

.github/FUNDING.yml

build: Create FUNDING.yml

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/JacksonUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/JacksonTest.java
core/src/test/java/com/tlcsdm/core/util/Order.java
core/src/test/java/com/tlcsdm/core/util/OrderLine.java
pom.xml
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/test/java/com/tlcsdm/smc/tool/GirretParserTest.java

feat: JacksonUtil重构, 支持yaml

---

.github/workflows/contributors.yml
CONTRIBUTORS.md

docs: 修改文档

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md
pom.xml

build: Add formsfx

---

pom.xml

build: Add help plugin

---

pom.xml

build: Add maven-assembly-plugin

---

.github/linters/.python-lint
.github/workflows/linter.yml
.gitignore
core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/test/java/com/tlcsdm/core/util/JythonTest.java
core/src/test/resources/jython/test.py
core/src/test/resources/jython/test1.py
docs/README.md
pom.xml

Fixes #909
1. ...
2. ...
3. ...

feat: Add jython support

---

.gitattributes
core/src/test/java/com/tlcsdm/core/util/JythonTest.java
core/src/test/resources/cpp/Decorator.cpp
core/src/test/resources/jython/cpplint.py

test: Add cpplint

---

core/pom.xml
core/src/test/java/com/tlcsdm/core/util/ViolationsTest.java
core/src/test/resources/violations/cppcheck/example1.xml
core/src/test/resources/violations/cppcheck/main.xml
pom.xml

test: Add violations-lib

---

core/src/test/java/com/tlcsdm/core/pmd/PmdTest.java

test: Add PMD

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md
pom.xml

feat: Add bytebuddy

---

core/pom.xml
core/src/main/java/module-info.java
pom.xml

build: Modify jython

---

cg/src/main/java/com/tlcsdm/cg/provider/CgBanner.java
frame/src/main/java/com/tlcsdm/frame/service/BannerPrinterService.java
qe/src/main/java/com/tlcsdm/qe/provider/QeBanner.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcBanner.java

Fixes #953
1. ...
2. ...
3. ...

fix(frame): 修改打包后BannerPrinterService加载异常

---

core/pom.xml

build: Modify bytebuddy scope

---

.github/workflows/qodana_code_quality.yml

build: Update qodana_code_quality.yml

---

smc/src/test/java/com/tlcsdm/smc/tool/CompareTest.java

test: Add test

---

pom.xml
smc/pom.xml

Fixes #985 
1. ...
2. ...
3. ...

build: Add license-maven-plugin

---

cg/pom.xml
demo/pom.xml
pom.xml
qe/pom.xml
smc/pom.xml

build: Improve build

---

pom.xml

Fixes #991 
1. ...
2. ...
3. ...

style: style code

---

jenkins/package.sh
jenkins/test.sh

build: Add jenkins shell

---

jenkins/package.sh

build: Modify jenkins shell

---

.gitignore
cg/pom.xml
common/pom.xml
core/pom.xml
demo/pom.xml
frame/pom.xml
jenkins/package.sh
login/pom.xml
pom.xml
qe/pom.xml
smc/pom.xml

Fixes #994
1. ...
2. ...
3. ...

build: Add flatten-maven-plugin

---

pom.xml

build: Add ciManagement

---

pom.xml

build: Modify config

---

core/src/main/java/com/tlcsdm/core/concurrent/VerboseRunnable.java
core/src/main/java/com/tlcsdm/core/concurrent/VerboseScheduledExecutorService.java
core/src/main/java/com/tlcsdm/core/event/ApplicationExitEvent.java
core/src/main/java/com/tlcsdm/core/event/ApplicationRestartEvent.java
core/src/main/java/com/tlcsdm/core/factory/config/ScheduledTaskExecutor.java
core/src/main/java/module-info.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #1036
1. ...
2. ...
3. ...

feat: Add ScheduledTaskExecutor

---

.github/workflows/issue-labeled.yml

ci: Add issue-deprecated workflow

---

.gitignore
.idea/runConfigurations/CgSampler.xml
.idea/runConfigurations/CommonSampler.xml
.idea/runConfigurations/QeSampler.xml
.idea/runConfigurations/SmcSampler.xml
cg/src/main/java/module-info.java
common/pom.xml
common/src/main/java/com/tlcsdm/jfxcommon/CommonSampler.java
common/src/main/java/module-info.java
common/src/main/resources/META-INF/services/com.tlcsdm.frame.service.FXSamplerProject
frame/src/main/java/com/tlcsdm/frame/model/EmptyCenterPanel.java
frame/src/main/java/com/tlcsdm/frame/util/SampleScanner.java

Fixes #1039 
1. ...
2. ...
3. ...

feat: Support common develop standalone

---

.idea/runConfigurations/ControlsFXSampler.xml
cg/pom.xml
pom.xml
qe/pom.xml
smc/pom.xml

ci: Modify maven-resources-plugin

---

pom.xml

Fixes #1047 
1. ...
2. ...
3. ...

build: Add asm config

---

demo/src/main/java/com/tlcsdm/demo/samples/HelloBorders.java
demo/src/main/java/module-info.java
pom.xml

feat: Modify demo Borders

---

.idea/runConfigurations/javafxTool_cg__package_.xml
.idea/runConfigurations/javafxTool_qe__package_.xml
.idea/runConfigurations/javafxTool_smc__package_.xml
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/resources/com/tlcsdm/core/i18n/messages_en.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_ja.properties
core/src/main/resources/com/tlcsdm/core/i18n/messages_zh.properties
smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

Fixes #1002
1. ...
2. ...
3. ...

feat: Improve get or download result

---

cg/src/main/java/com/tlcsdm/cg/provider/CgMenubarConfigrationProvider.java
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

Fixes #1063
1. ...
2. ...
3. ...

feat: 优化about中链接过长的问题

---

core/src/main/java/com/tlcsdm/core/javafx/util/Keys.java
frame/src/main/java/com/tlcsdm/frame/FXSampler.java

Fixes #1062
1. ...
2. ...
3. ...

feat: Add Keys.UseDevMode and initializeProperties

---

smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/HconvertExcel.java

Fixes #1074 
1. ...
2. ...
3. ...

feat(smc): GirretReview适配girret 3.9

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/HtmlEscape.java
common/src/main/java/com/tlcsdm/jfxcommon/tools/MoneyToChinese.java
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_en.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_ja.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_zh.properties
core/src/main/java/com/tlcsdm/core/javafx/controlsfx/FxAction.java
core/src/main/java/com/tlcsdm/core/javafx/util/TooltipUtil.java
qe/src/main/java/com/tlcsdm/qe/tools/Compress.java
qe/src/main/java/com/tlcsdm/qe/tools/DaliDemo.java
qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java
smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/tools/CodeStyleLength120.java
smc/src/main/java/com/tlcsdm/smc/tools/GirretReview.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/HconvertExcel.java
smc/src/main/java/com/tlcsdm/smc/unitTest/SpecGeneralTest.java

Fixes #1065
1. ...
2. ...
3. ...

build: Upgrade sample version

---

.gitignore
core/src/main/java/com/tlcsdm/core/dsl/DSL.java
core/src/main/java/com/tlcsdm/core/dsl/commands/DSLCommandType.java
core/src/main/java/com/tlcsdm/core/dsl/commands/DSLDefinedCommand.java
core/src/main/java/com/tlcsdm/core/dsl/commands/FunctionRunnable.java
core/src/main/java/com/tlcsdm/core/dsl/commands/VariableRunnable.java
core/src/main/java/com/tlcsdm/core/dsl/runtime/DSLRuntime.java
core/src/main/java/com/tlcsdm/core/dsl/runtime/DSLRuntimeCommand.java
core/src/main/java/com/tlcsdm/core/dsl/stringvars/OriginalReturnString.java
core/src/main/java/com/tlcsdm/core/dsl/stringvars/ReturnStringFromKey.java
core/src/main/java/com/tlcsdm/core/dsl/stringvars/StringVars.java
core/src/main/java/com/tlcsdm/core/util/SplitUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/dsl/DSLDriverTest.java
core/src/test/java/com/tlcsdm/core/dsl/ExampleDSL.java
core/src/test/java/com/tlcsdm/core/dsl/ExampleDSLStrictMode.java
core/src/test/java/com/tlcsdm/core/dsl/README.md
core/src/test/java/com/tlcsdm/core/dsl/StringVarsTest.java
core/src/test/resources/util/dsl/ExampleDSLConfig

Fixes #1082
1. ...
2. ...
3. ...

feat: Add DSL tool

---

core/src/main/java/com/tlcsdm/core/dsl/impl/IterateINI.java
core/src/main/java/com/tlcsdm/core/dsl/impl/KeyValuePairFound.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/dsl/IterateINITest.java
core/src/test/resources/util/dsl/example.ini

Fixes #1029 
1. ...
2. ...
3. ...

feat: Add IterateINI for DSL

---

qodana.yaml

ci: Update qodana.yaml

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
pom.xml

build: Improve javadoc

---

smc/src/main/java/com/tlcsdm/smc/codeDev/DmaTriggerSourceCode.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/AbstractEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/C1MEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2AEcmScript.java
smc/src/main/java/com/tlcsdm/smc/codeDev/ecm/U2CEcmScript.java
smc/src/main/java/com/tlcsdm/smc/unitDesign/DtsTriggerSourceDoc.java

Fixes #1058
1. ...
2. ...
3. ...

feat(smc): Improve download action

---

core/src/main/java/com/tlcsdm/core/javafx/control/Borders.java

Fixes #1054
1. ...
2. ...
3. ...

feat(core): Add Borders

---

cg/src/main/java/com/tlcsdm/cg/provider/CgMenubarConfigrationProvider.java
core/src/main/java/com/tlcsdm/core/javafx/factory/KeyCombinationFactory.java
core/src/main/java/module-info.java
demo/src/main/java/com/tlcsdm/demo/FXMenubarConfigration.java
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
smc/src/main/java/com/tlcsdm/smc/provider/SmcMenubarConfigrationProvider.java

Fixes #1043
1. ...
2. ...
3. ...

feat: Add KeyCombination

---

pom.xml

Fixes #1077 
1. ...
2. ...
3. ...

feat: Support h2

---

pom.xml

Fixes #1096
1. ...
2. ...
3. ...

build: Add jcommander

---

core/src/main/java/com/tlcsdm/core/freemarker/template/HexDirective.java
core/src/test/java/com/tlcsdm/core/util/FreemarkerTest.java
core/src/test/java/com/tlcsdm/core/util/HexTest.java
core/src/test/resources/freemarker/templates/hex.ftl
core/src/test/resources/freemarker/templates/repeat.ftl

Fixes #1057
1. ...
2. ...
3. ...

feat: Add HexDirective

---

core/src/main/java/com/tlcsdm/core/factory/config/TemplateLoaderScanner.java

feat(core): Improve TemplateLoaderScanner

---

pom.xml

build: Upgrade groovy

---

core/src/main/java/com/tlcsdm/core/freemarker/FitClassTemplateLoader.java
demo/pom.xml

Fixes #1101, Fixes #1103
1. ...
2. ...
3. ...

feat: Improve freemarker

---

jenkins/package.sh

ci: Update package.sh

---

.github/labeler.yml
.gitignore
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

Fixes #1115
1. ...
2. ...
3. ...

ci: Add vscode config

---

.editorconfig
.github/labeler.yml
.github/workflows/linter.yml
.gitignore
.idea/artifacts/javafxTool_cg_mac_jar.xml
.idea/artifacts/javafxTool_cg_win_jar.xml
.idea/artifacts/javafxTool_qe_mac_jar.xml
.idea/artifacts/javafxTool_qe_win_jar.xml
.idea/artifacts/javafxTool_smc_mac_jar.xml
.idea/artifacts/javafxTool_smc_win_jar.xml
.idea/codeStyles/Default.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/dictionaries
.idea/fileTemplates/code/I18nized Concatenation.java
.idea/fileTemplates/code/I18nized Expression.java
.idea/fileTemplates/internal/AnnotationType.java
.idea/fileTemplates/internal/Class.java
.idea/fileTemplates/internal/Enum.java
.idea/fileTemplates/internal/Interface.java
.idea/fileTemplates/internal/JavaFXApplication.java
.idea/fileTemplates/internal/Kotlin Class.kt
.idea/fileTemplates/internal/Kotlin Enum.kt
.idea/fileTemplates/internal/Kotlin Interface.kt
.idea/fileTemplates/internal/Record.java
.settings/clean.launch
qodana.yaml

Fixes #1116
1. ...
2. ...
3. ...

build: Add idea config

---

.idea/jarRepositories.xml

ci: Add idea config

---

.gitattributes

ci: modify config

---

.idea/codeStyles/Default.xml
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml

ci: Modify idea config

---

core/src/main/java/com/tlcsdm/core/logging/logback/CoreConfigurator.java
core/src/main/java/com/tlcsdm/core/logging/logback/CoreJoranConfigurator.java
core/src/main/java/com/tlcsdm/core/logging/logback/WorkEnvAction.java
core/src/main/java/com/tlcsdm/core/logging/logback/WorkEnvIfNestedWithinSecondPhaseElementSanityChecker.java
core/src/main/java/com/tlcsdm/core/logging/logback/WorkEnvModel.java
core/src/main/java/com/tlcsdm/core/logging/logback/WorkEnvModelHandler.java
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/module-info.java
core/src/main/resources/META-INF/services/ch.qos.logback.classic.spi.Configurator
smc/src/main/resources/logback.xml

Fixes #1126
1. ...
2. ...
3. ...

feat: Improve logback

---

core/src/main/java/com/tlcsdm/core/javafx/chart/DynamicChart.java
core/src/main/java/com/tlcsdm/core/javafx/chart/DynamicXYChart.java
core/src/main/java/com/tlcsdm/core/javafx/chart/LineChartWithMarkers.java
core/src/main/java/com/tlcsdm/core/javafx/control/LongSpinnerValueFactory.java
core/src/main/java/com/tlcsdm/core/javafx/control/UnboundedDoubleSpinnerValueFactory.java
core/src/main/java/com/tlcsdm/core/javafx/util/TextFormatterUtil.java
core/src/main/java/module-info.java
qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java

Fixes #1129
1. ...
2. ...
3. ...

feat: Add chart support

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/database/DataBaseType.java
core/src/main/java/com/tlcsdm/core/database/DataSourceUtil.java
core/src/main/java/com/tlcsdm/core/database/DataSourceUtilFactory.java
core/src/main/java/com/tlcsdm/core/database/DataSourceUtilTypes.java
core/src/main/java/com/tlcsdm/core/database/DruidDataSourceUtil.java
core/src/main/java/com/tlcsdm/core/database/HikariDataSourceUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/ConfigureUtil.java
core/src/main/java/com/tlcsdm/core/util/DependencyUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/database/H2Test.java
pom.xml
qodana.yaml

Fixes #1077
1. ...
2. ...
3. ...

feat: Add DataSourceUtil

---

frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/com/tlcsdm/frame/service/impl/DefaultEasterEggService.java

Fixes #1083
1. ...
2. ...
3. ...

fix: fix DefaultEasterEggService close fail

---

core/src/main/java/com/tlcsdm/core/util/ProcessUtil.java

Fixes #1030
1. ...
2. ...
3. ...

feat: Add ProcessUtil

---

LICENSE
cg/src/main/java/com/tlcsdm/cg/util/CgConstant.java
pom.xml
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
smc/src/main/java/com/tlcsdm/smc/util/SmcConstant.java

build: Modify year

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiff.java

Fixes #1059 
1. ...
2. ...
3. ...

feat: Improve fileDiff

---

.github/workflows/artifact.yml

ci: Create artifact.yml

---

.github/workflows/artifact.yml

ci: Update artifact.yml

---

frame/src/main/java/com/tlcsdm/frame/service/impl/DefaultEasterEggService.java

fix: 修复日期判断问题

---

.github/workflows/artifact.yml
.github/workflows/rebase.yml

Fixes #1156
1. ...
2. ...
3. ...

ci: Add rebase

---

core/src/main/java/com/tlcsdm/core/util/ColorUtil.java
core/src/test/java/com/tlcsdm/core/util/ColorUtilTest.java

Fixes #1165
1. ...
2. ...
3. ...

feat: Add ColorUtil

---

core/src/main/java/com/tlcsdm/core/concurrent/AbstractWeakConcurrentMap.java
core/src/main/java/com/tlcsdm/core/concurrent/DetachedThreadLocal.java
core/src/main/java/com/tlcsdm/core/concurrent/WeakConcurrentMap.java
core/src/main/java/com/tlcsdm/core/concurrent/WeakConcurrentSet.java
core/src/test/java/com/tlcsdm/core/concurrent/DetachedThreadLocalTest.java
core/src/test/java/com/tlcsdm/core/concurrent/WeakConcurrentMapTest.java
core/src/test/java/com/tlcsdm/core/concurrent/WeakConcurrentSetTest.java

Fixes #1170
1. ...
2. ...
3. ...

feat: Add WeakConcurrent

---

core/src/main/java/com/tlcsdm/core/javafx/control/CustomTextField.java
core/src/main/java/com/tlcsdm/core/javafx/control/RangeSlider.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/CustomTextFieldSkin.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/RangeSliderSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/customtextfield.css
core/src/main/resources/com/tlcsdm/core/static/javafx/control/rangeslider.css
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

Fixes #1175
1. ...
2. ...
3. ...

feat: Add RangeSlider

---

core/src/main/java/com/tlcsdm/core/util/ColorUtil.java
core/src/test/java/com/tlcsdm/core/util/ColorUtilTest.java

Fixes #1185
1. ...
2. ...
3. ...

feat: Add coor2Rgb

---

core/pom.xml
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/JsscTest.java
pom.xml

Fixes #1194
1. ...
2. ...
3. ...

feat: Add Jssc

---

core/src/test/java/com/tlcsdm/core/util/JnaTest.java

Fixes #831
1. ...
2. ...
3. ...

test: Add JnaTest

---

core/src/main/java/com/tlcsdm/core/javafx/controller/CoreStorageHandler.java
core/src/main/java/com/tlcsdm/core/javafx/controller/PreferencesView.java
core/src/main/java/com/tlcsdm/core/javafx/util/Keys.java

Fixes #1176
1. ...
2. ...
3. ...

feat: Improve preference

---

README.md
README_jp.md
README_zh.md
docs/README.md
docs/index.html
docs/overview/Into.md

Fixes #1204
1. ...
2. ...
3. ...

docs: Modify docs

---

.github/workflows/artifact.yml

ci: Modify workflow

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/oshi/CpuInfo.java
core/src/main/java/com/tlcsdm/core/oshi/CpuTicks.java
core/src/main/java/com/tlcsdm/core/oshi/OshiUtil.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/oshi/OshiTest.java
pom.xml

Fixes #1215
1. ...
2. ...
3. ...

build: Add oshi

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiff.java
common/src/main/java/com/tlcsdm/jfxcommon/tools/FileDiffWithWeb.java
smc/pom.xml
smc/src/main/java/module-info.java

Fixes #1223
1. ...
2. ...
3. ...

feat: Add FileDiffWithWeb

---

core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield.java
core/src/main/java/com/tlcsdm/core/util/ColourUtil.java
core/src/test/java/com/tlcsdm/core/javafx/DemoDecorationTextfieldApp.java
core/src/test/java/com/tlcsdm/core/javafx/IssueSearchableComboBoxApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/DemoDecorationTextfield.java
core/src/test/java/com/tlcsdm/core/javafx/control/IssueSearchableComboBox.java
pom.xml

Fixes #1230 Fixes #1227
1. ...
2. ...
3. ...

feat: Improve ColourUtil and DecorationTextfield

---

core/src/main/java/com/tlcsdm/core/javafx/control/CustomTextField.java
core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield.java
core/src/main/java/com/tlcsdm/core/javafx/control/Severity.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/RangeSliderSkin.java
demo/pom.xml
login/pom.xml
pom.xml

Fixes #1235
1. ...
2. ...
3. ...

feat: Improve RangeSlider

---

cg/src/main/resources/logback.xml
core/pom.xml
core/src/main/java/com/tlcsdm/core/concurrent/VerboseScheduledExecutorService.java
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/com/tlcsdm/core/util/HashUtil.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/main/java/module-info.java
docs/README.md
pom.xml
qe/src/main/resources/logback.xml
smc/src/main/resources/logback.xml

Fixes #1234
1. ...
2. ...
3. ...

feat: Use classgraph instead of reflections

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md
pom.xml

Fixes #1239 Fixes #1241
1. ...
2. ...
3. ...

feat: Add checker-qual

---

core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/com/tlcsdm/core/util/DiffHandleUtil.java

Fixes #1226
1. ...
2. ...
3. ...

fix: Fix getDiffHtml error

---

jenkins/win/cg/README.md
jenkins/win/cg/cgTool.vbs
jenkins/win/cg/console.bat
jenkins/win/qe/README.md
jenkins/win/qe/console.bat
jenkins/win/qe/qeTool.bat
jenkins/win/smc/README.md
jenkins/win/smc/console.bat
jenkins/win/smc/smcTool.bat
jenkins/win/smc/smcTool.vbs
jenkins/win/smcTool.vbs

Fixes #1248
1. ...
2. ...
3. ...

ci: Modify script

---

core/src/main/java/com/tlcsdm/core/javafx/control/Borders.java

Fixes #1254
1. ...
2. ...
3. ...

feat: Improve Borders

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/javafx/control/ScalableContentPane.java
core/src/main/java/com/tlcsdm/core/javafx/control/ScaleBehavior.java
core/src/test/java/com/tlcsdm/core/javafx/ExplicitContentTest.java
core/src/test/java/com/tlcsdm/core/javafx/ImplicitContentTest.java
core/src/test/java/com/tlcsdm/core/javafx/ScalableContentPaneApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/ScalableContentPaneDemo.java
core/src/test/resources/javafx/explicit_content.fxml
core/src/test/resources/javafx/implicit_content.fxml

Fixes #1252
1. ...
2. ...
3. ...

feat: Improve ScalableContentPane

---

core/src/main/java/com/tlcsdm/core/javafx/control/CustomTextField.java
core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/CustomTextFieldSkin.java
core/src/main/java/module-info.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/customtextfield.css
core/src/test/java/com/tlcsdm/core/javafx/control/DemoDecorationTextfield.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

Fixes #1231
1. ...
2. ...
3. ...

feat: Improve DecorationTextfieldSkin

---

core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield.java
core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield2.java
core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTextfield3.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationTextfieldSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/decorationtextfield.css
core/src/test/java/com/tlcsdm/core/javafx/control/DemoDecorationTextfield.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

Fixes #1231
1. ...
2. ...
3. ...

feat: Improve CustomTextField

---

pom.xml

Closes #1263
Fixes #
1. ...
2. ...
3. ...

build: Improve pom

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/module-info.java
core/src/test/java/com/tlcsdm/core/util/Zip4jTest.java
pom.xml

Fixes #1273 
1. ...
2. ...
3. ...

feat: Add zip4j

---

jenkins/win/cg/cgTool.bat
jenkins/win/qe/qeTool.bat
jenkins/win/smc/smcTool.bat

Close #1283
Fixes #
1. ...
2. ...
3. ...

fix: Build result error

---

core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java

由指定扫描com.tlcsdm改为排除其他package扫描
Fixes #1276
1. ...
2. ...
3. ...

feat: Improve InterfaceScanner

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/test/java/com/tlcsdm/core/util/PlantumlTest.java
core/src/test/resources/plantuml/core.puml
core/src/test/resources/plantuml/smc.puml
pom.xml
smc/pom.xml

Fixes #1278
1. ...
2. ...
3. ...

feat: Add plantuml

---

core/src/main/java/com/tlcsdm/core/javafx/control/DecorationTitlePane.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationTextfieldSkin.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationTitlePaneSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/decorationtitlepane.css
core/src/test/java/com/tlcsdm/core/javafx/DecorationTitlePaneApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/DecorationTitlePaneTest.java

Fixes #1240
1. ...
2. ...
3. ...

feat: Improve DecorationTitlePane

---

core/src/main/java/com/tlcsdm/core/javafx/control/DecorationComboBox.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationComboBoxSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/decorationcombobox.css
core/src/test/java/com/tlcsdm/core/javafx/DecorationComboBoxApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/DecorationComboBoxTest.java

Fixes #1229
1. ...
2. ...
3. ...

feat: Add DecorationComboBox

---

.github/workflows/artifact.yml
core/src/main/java/com/tlcsdm/core/javafx/control/ResizePane.java
core/src/main/java/com/tlcsdm/core/javafx/control/ZoomImageView.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/ResizePaneSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/resize-pane.css
core/src/test/java/com/tlcsdm/core/javafx/ResizePaneApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/ResizePaneDemo.java
core/src/test/resources/javafx/resize-pane-demo.fxml

Fixes #1290
1. ...
2. ...
3. ...

feat: Add ResizePane

---

core/pom.xml
core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/main/java/com/tlcsdm/core/util/FreemarkerUtil.java
core/src/test/java/com/tlcsdm/core/freemarker/FreemarkerTest.java
core/src/test/resources/freemarker/templates/dom.ftl
core/src/test/resources/freemarker/test.xml

Fixes #1242 
1. ...
2. ...
3. ...

feat: Improve FreemarkerTest

---

core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationComboBoxSkin.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationTextfieldSkin.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationTitlePaneSkin.java

Fixes #1311
1. ...
2. ...
3. ...

feat: Improve DecorationComboBox

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
frame/pom.xml
frame/src/main/java/com/tlcsdm/frame/FXSampler.java
frame/src/main/java/module-info.java
pom.xml

Fixes #1314
1. ...
2. ...
3. ...

feat: Add cssfx

---

.github/workflows/artifact.yml

ci: Improve workflow

---

pom.xml

Fixes #1315
1. ...
2. ...
3. ...

build: Add maven-enforcer-plugin

---

pom.xml

Fixes #1323
1. ...
2. ...
3. ...

ci: Improve exec-maven-plugin

---

pom.xml

Fixes #1319
1. ...
2. ...
3. ...

build: Add git-commit-id-maven-plugin

---

pom.xml

Fixes #1322
1. ...
2. ...
3. ...

build: Add maven-checkstyle-plugin

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
docs/README.md
pom.xml

build: Upgrade javafx to 21.0.2

---

.github/workflows/automerge.yml

ci: Update automerge.yml

---

cg/pom.xml
cg/src/main/java/com/tlcsdm/cg/provider/CgMenubarConfigrationProvider.java
cg/src/main/java/com/tlcsdm/cg/util/CgConstant.java
cg/src/main/java/module-info.java
core/pom.xml
core/src/main/java/com/tlcsdm/core/httpserver/SimpleHttpServer.java
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/module-info.java
pom.xml
qe/pom.xml
qe/src/main/java/com/tlcsdm/qe/provider/QeMenubarConfigrationProvider.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java
qe/src/main/java/com/tlcsdm/qe/util/QeConstant.java
qe/src/main/java/module-info.java

Fixes #1340
1. ...
2. ...
3. ...

feat: Use teenyhttpd instead of hutool-http

---

.github/labeler.yml
.mvn/jvm.config
.mvn/maven.config
smc/pom.xml
smc/src/main/java/module-info.java

ci: Add maven config

---

.gitignore
common/pom.xml
pom.xml

ci: Improve version config

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/escape/HtmlEscape.java
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_en.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_ja.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_zh.properties
core/pom.xml

feat: Improve HtmlEscape

---

core/src/main/java/com/tlcsdm/core/javafx/control/Switch.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/switch.css
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

Fixes #1348
1. ...
2. ...
3. ...

feat: Add Switch

---

pom.xml

Fixes #1351 
1. ...
2. ...
3. ...

feat: Add properties-maven-plugin

---

core/src/main/java/com/tlcsdm/core/freemarker/code/AbstractFreemarkerTemplateFile.java
core/src/main/java/com/tlcsdm/core/freemarker/code/DefaultFreemarkerTemplate.java
core/src/main/java/com/tlcsdm/core/freemarker/code/ITemplateFile.java
core/src/main/java/com/tlcsdm/core/freemarker/directive/HexDirective.java
core/src/main/java/module-info.java
core/src/test/resources/freemarker/templates/hex.ftl
core/src/test/resources/freemarker/templates/regor.ftl

Fixes #1361
1. ...
2. ...
3. ...

feat: improve freemarker code

---

core/src/main/java/com/tlcsdm/core/util/CoreUtil.java
core/src/test/java/com/tlcsdm/core/freemarker/CodeGenTest.java

Fixes #1366
1. ...
2. ...
3. ...

test: Add CodeGenTest

---

core/src/main/java/com/tlcsdm/core/javafx/control/SubmitButton.java
core/src/test/java/com/tlcsdm/core/javafx/SubmitButtonApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/SubmitButtonTest.java

Fixes #1363
1. ...
2. ...
3. ...

feat: Add SubmitButton

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
pom.xml

Fixes #1378 
1. ...
2. ...
3. ...

feat: Add common-email

---

core/src/test/java/com/tlcsdm/core/util/ProcessBuilderTest.java

Fixes #1384 
1. ...
2. ...
3. ...

test: Add ProcessBuilderTest

---

core/src/test/java/com/tlcsdm/core/javafx/ComboBoxListenerApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/ComboBoxListenerTest.java

Fixes #1382
1. ...
2. ...
3. ...

test: Add ComboBoxListenerTest

---

core/src/main/java/com/tlcsdm/core/javafx/control/DecorationCheckBox.java
core/src/main/java/com/tlcsdm/core/javafx/control/skin/DecorationCheckBoxSkin.java
core/src/main/resources/com/tlcsdm/core/static/javafx/control/decorationcheckbox.css
core/src/test/java/com/tlcsdm/core/javafx/DecorationCheckBoxApp.java
core/src/test/java/com/tlcsdm/core/javafx/control/DecorationCheckBoxTest.java

Fixes #1377
1. ...
2. ...
3. ...

feat: Add DecorationCheckBox

---

.gitignore
common/src/main/java/com/tlcsdm/jfxcommon/tools/image/IconTool.java
common/src/main/java/module-info.java
common/src/main/resources/com/tlcsdm/jfxcommon/fxml/iconTool.fxml
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_en.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_ja.properties
common/src/main/resources/com/tlcsdm/jfxcommon/i18n/messages_zh.properties
common/src/main/resources/com/tlcsdm/jfxcommon/static/data/iosAppIcon/Contents.json

Fixes #1016
1. ...
2. ...
3. ...

feat: Add IconTool

---

pom.xml

ci: Fix license-maven-plugin build error

---

pom.xml

ci: Improve maven-surefire-plugin

---

core/src/test/java/com/tlcsdm/core/util/CSTest.java
core/src/test/resources/util/sample.mtpj

Fixes #1402
1. ...
2. ...
3. ...

test: Add CSTest

---

pom.xml

build: Add commons-codec

---

pom.xml

build: Add commons-logging

---

cg/src/main/resources/logback.xml
core/pom.xml
core/src/main/java/com/tlcsdm/core/factory/config/ThreadPoolTaskExecutor.java
core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
core/src/main/java/com/tlcsdm/core/util/InterfaceScanner.java
core/src/main/java/module-info.java
docs/README.md
qe/src/main/resources/logback.xml
smc/src/main/resources/logback.xml

打包后classgraph扫描不到classpath
Fixes #
1. ...
2. ...
3. ...

fix: Use reflections instead of classgraph

---

pom.xml

build: 排除jackson-databind的byte-buddy

---

jenkins/log-parser-rules

Fixes #1434
Fixes #
1. ...
2. ...
3. ...

ci: Create log-parser-rules

---

.gitignore
common/src/main/java/com/tlcsdm/jfxcommon/tools/image/IconTool.java
core/src/main/java/com/tlcsdm/core/database/DataSourceUtil.java
core/src/main/java/com/tlcsdm/core/javafx/control/NumberSpinner.java
core/src/main/java/com/tlcsdm/core/javafx/stage/PdfViewStage.java
core/src/main/java/com/tlcsdm/core/javafx/util/FileChooserUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/ImageUtil.java
core/src/main/java/com/tlcsdm/core/javafx/util/ImgToolUtil.java
core/src/main/java/com/tlcsdm/core/logging/logback/WorkEnvAction.java
core/src/main/java/com/tlcsdm/core/util/VoskUtil.java
core/src/test/java/com/tlcsdm/core/freemarker/FreemarkerTest.java
core/src/test/java/com/tlcsdm/core/util/CSTest.java
core/src/test/java/com/tlcsdm/core/util/CaffeineTest.java
core/src/test/java/com/tlcsdm/core/util/CryptoTest.java
core/src/test/java/com/tlcsdm/core/util/PdfboxTest.java
core/src/test/java/com/tlcsdm/core/util/Zip4jTest.java
demo/src/main/java/com/tlcsdm/demo/samples/HelloBorders.java
demo/src/main/java/com/tlcsdm/demo/samples/spreadsheet/HelloSpreadsheetView.java
demo/src/main/java/com/tlcsdm/demo/samples/spreadsheet/HelloSpreadsheetView2.java
pom.xml
qe/src/main/java/com/tlcsdm/qe/tools/FxmlDemo.java
qe/src/main/java/com/tlcsdm/qe/tools/TestTool.java

Fixes #1443
1. ...
2. ...
3. ...

feat: Add impsort-maven-plugin

---

common/src/main/java/com/tlcsdm/jfxcommon/tools/image/IconTool.java
common/src/main/resources/com/tlcsdm/jfxcommon/fxml/iconTool.fxml

feat: Improve iconTool

---

core/src/test/java/com/tlcsdm/core/util/CSTest.java
core/src/test/java/com/tlcsdm/core/util/YuiCompressTest.java

test: Improve test

---

core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java
pom.xml

Closes 1458
[skip ci]
Fixes #
1. ...
2. ...
3. ...

build: Add java-util

---

core/src/test/java/com/tlcsdm/core/freemarker/Book.java
core/src/test/java/com/tlcsdm/core/freemarker/Category.java
core/src/test/java/com/tlcsdm/core/freemarker/FreemarkerTest.java
core/src/test/resources/freemarker/templates/javabean.ftl

Closes #1461
Fixes #
1. ...
2. ...
3. ...

test: Improve freemarker for javabean

---

core/src/main/java/com/tlcsdm/core/util/HttpUtil.java
core/src/test/java/com/tlcsdm/core/util/HttpClientTest.java

test: Add HttpClientTest

---

sweep.yaml

ci: Update sweep.yaml

---

core/src/test/java/com/tlcsdm/core/freemarker/FreemarkerTest.java
core/src/test/java/com/tlcsdm/core/freemarker/Memento.java
core/src/test/java/com/tlcsdm/core/freemarker/MementoModel.java
core/src/test/java/com/tlcsdm/core/freemarker/MementoObjectWrapper.java
core/src/test/java/com/tlcsdm/core/freemarker/MementoService.java
core/src/test/java/com/tlcsdm/core/freemarker/ReadOnlyMemento.java
core/src/test/resources/freemarker/memento.xml
core/src/test/resources/freemarker/templates/memento.ftl

test: Improve freemarker objectWrapper

---

core/pom.xml
core/src/test/java/com/tlcsdm/core/util/EclipseCollectionsTest.java
pom.xml

Fixes #1521
1. ...
2. ...
3. ...

test: Test for eclipse-collections

---

core/pom.xml
pom.xml

build: Add jep

---

pom.xml

Fixes #1537
1. ...
2. ...
3. ...

build: Add jaxb

---

pom.xml

build: Improve maven-checkstyle-plugin

---

.github/workflows/check-aliyun-maven.yml

ci: 修复工作流问题
